### ISSUE TITLE
Print not working on Windows

### ISSUE THREAD

**Issue by emattei** [IGVF/seqspec#13]
`!seqspec print broad_human_jamboree_test_spec.yaml`
Returns
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\eugen\AppData\Local\Programs\Python\Python311\Scripts\seqspec.exe\__main__.py", line 7, in <module>
  File "C:\Users\eugen\AppData\Local\Programs\Python\Python311\Lib\site-packages\seqspec\main.py", line 68, in main
    COMMAND_TO_FUNCTION[sys.argv[1]](parser, args)
  File "C:\Users\eugen\AppData\Local\Programs\Python\Python311\Lib\site-packages\seqspec\seqspec_print.py", line 45, in validate_print_args
    print(s)
  File "C:\Users\eugen\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-10: character maps to <undefined>
```

Apparently this bug is due to this:
https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters

Works on Mac and Linux but not on jupyter notebook run under Windows.

Tested using the spec.yaml found in the GitHub under the examples.

**Comment by sbooeshaghi** [comment]
Is this still an issue?

**Comment by sbooeshaghi** [comment]
Ping

**Comment by emattei** [comment]
Yes, it works now! Closing the issue.
